/*
 *	This file contains data for different versions of FW
 *	It is possible that support for some more may need to be added
 */

#ifndef _COMMON_H_
#define _COMMON_H_

#include <stdio.h>
#include "functions.h"
#include "cex2dex.h"

#define KERNEL_BASE					0x8000000000000000ULL
#define KERNEL_ADDRESS(x)			(KERNEL_BASE | (uint32_t)(x))
#define SYSCALL_OPD_PTR_OFFSET(n)	((lv2_peek(CEX_OFFSET) == CEX || lv2_peek(CEX_OFFSET - 0x10) == CEX ? SYSCALL_TABLE_OFFSET : lv2_peek(DEX_OFFSET) == DEX ? SYSCALL_TABLE_DEX_OFFSET : SYSCALL_TABLE_DEH_OFFSET) + (n) * sizeof(uint64_t))
#define SYSCALL_OPD_OFFSET(n)		lv2_peek(SYSCALL_OPD_PTR_OFFSET(n))

#define EID_ROOT_KEY_SIZE			0x30

/* Firmware specific defines */
#define TOC_OFFSET					KERNEL_ADDRESS(0x34FBB0)
#define TOC_490_OFFSET				KERNEL_ADDRESS(0x34FBA0)
#define	REDIRECT_OFFSET				KERNEL_ADDRESS(0x2A0F58)
#define	REDIRECT_490_OFFSET			KERNEL_ADDRESS(0x2A0F4C)
#define SYSCALL_TABLE_OFFSET		KERNEL_ADDRESS(0x363BE0)

#define TOC_DEX_OFFSET				KERNEL_ADDRESS(0x3759C0)
#define SYSCALL_TABLE_DEX_OFFSET	KERNEL_ADDRESS(0x38A4E8)
#define	REDIRECT_DEX_OFFSET			KERNEL_ADDRESS(0x2BC1D4)

#define TOC_DEH_OFFSET				KERNEL_ADDRESS(0x39D440)
#define SYSCALL_TABLE_DEH_OFFSET	KERNEL_ADDRESS(0x3B28F8)
#define	REDIRECT_DEH_OFFSET			KERNEL_ADDRESS(0x2D226C)

#define PAYLOAD_OFFSET				KERNEL_ADDRESS(0x7F0000)
#define PAYLOAD_OPD_OFFSET			KERNEL_ADDRESS(0x1630)

#define HTAB_BASE					KERNEL_ADDRESS(0xF000000)
#define HTAB_SIZE					0x40000ULL
#define HTAB_ENTRY_SIZE				0x10

#define SYSCALL_RUN_PAYLOAD			32
#define SYSCALL_HVC_REDIRECTOR		811

#endif
